### ISSUE TITLE
kp open <database>

### ISSUE THREAD

**Issue by git-lara** [mvarendorff/KeePass2Flow#3]
I would need support.

Step 1: The window "Authorize a new connection" pops up with the code in red which I enter.

Step 2 show already my database (I have one).

But: kp "mail"
does not work, it opens keepass itself and the text in flow launcher changes to "kp open" again.

And the window "Authorize a new connection" on KeePass is still there.

Which step is wrong?

Thank you in advance.

**Comment by mvarendorff** [comment]
Hey, sorry for taking some time to reply!

I believe there is still some buginess within the authentication logic that breaks on some combinations of keys and I have yet to find out when this occurs.

For now, the KeePass RPC code *should* change each time so if you keep doing `kp auth ` with the code, it should function eventually, I believe (which I am aware is not a great UX) but I'll try to find some time today to find the root cause of when keys are not accepted!

**Comment by mattthhh** [comment]
Any news ?

**Comment by mvarendorff** [comment]
I'm afraid there has not been, sorry! And sorry for the lack of communication on this!

The reason this happens is some fault in the SRP-implementation which are annoyingly hard to track down.

I am considering building up a test-suite of different SRP parameters to hopefully cover all cases. For that I want to add a new command tomorrow that allows dumping debug information to paste here (none of which concerns your actual database and passwords but only the SRP parameters used between KeePass RPC and this plugin) so I can get some more insight into what happens there.

**Comment by mvarendorff** [comment]
@mattthhh @git-lara I just released v1.1.3 of the plugin; it might take a moment for the update to show up on the plugin page within FlowLauncher.

To make sure no old keys are lingering around, please follow these steps:

1. Open Windows Credential Manager
2. Select "Windows Credentials"
3. Under "Generic Credentials" search for the entry "KeePass2Flow-kpflow2" and remove it (if present)
4. Restart Flow Launcher (if you removed an entry under 3)

After that you should be prompted for auth by KeePassRPC again as before.

Should there still be issues, let me know!

**Comment by git-lara** [comment]
Now it connects to the database but kp search is not possible. Only kp open. Once I do kp open, flow launcher closes itself, so I have to restart flow launcher.

**Comment by oremir** [comment]
Same issue here. kp open doesn´t do anything. Just freeze.

**Comment by mvarendorff** [comment]
I could reproduce the issue now locally although it seems that this behaviour is not consistent with varying keys, so dropping the key as described [here](https://github.com/mvarendorff/KeePass2Flow/issues/3#issuecomment-2543564019) should eventually lead to a key that works. Definitely not the way this plugin is supposed to work though...

I'll take another look and post an update here once I found the cause 👍

**Comment by oremir** [comment]
Thank you. But it just resets conetion. But I connected correctly for the first time and for the second time as well.

But still can´t open database.

**Comment by oremir** [comment]
I set database manualy in the plugin setup. And it search now. But nothing else. Can I ask what should it do actually? I can search entry I know I have it in. But when I press enter, it just opens KeePass app (even doesn´t find the entry). I thought it will allow me copy password in clipboard or something like that.

**Comment by mvarendorff** [comment]
Once I fixed the key-exchange properly, that's exactly what it does. I created an issue to document the usage of the plugin a bit better but this GIF shows what it's supposed to do:

![notepad_y3DWiAYREC](https://github.com/user-attachments/assets/03fb49d3-9ddc-4b83-9512-1d65e924b6e3)

Essentially the workflow is:

1. `kp open database-name` -> Opens the database and connects KeePassRPC
2. `kp password-entry-name` -> Searches for the entry with the given name
3. Hit <kbd>Enter</kbd> -> Copies the password for the entry in your clipboard (erased after 5 seconds) - Optionally you can also do <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to copy the username to your clipboard

**Comment by mvarendorff** [comment]
A short update to `kp open` crashing FlowLauncher: I believe I managed to track down the root cause of this but I don't have a fix yet. Hopefully before the end of the week 🤞

**Comment by oremir** [comment]
Great! It works now ♥️ Thank you so much.

**Comment by mvarendorff** [comment]
I just released version 1.1.4 of the plugin which I am relatively confident fixes the issue of an incorrect key being stored. It also contains a fix for an incorrect key causing an immediate crash of Flow.Launcher - instead it now attempts to agree on a new key. Lastly, a new action `kp reconnect` is available that automates the 4 step reset of a stored key outlined above.

As with the last update, it might take a moment for the new version to become available in Flow's plugin store.

**Comment by git-lara** [comment]
It finally works :-)
